testscript{*}: test = $recall($build.path)

testscript{*}:
{
  test.options += --no-default-options --serial-stop

  project_src = [dir_path] $src_root

  tailwind = $tailwind_exe
  tailwind_sha256 = $tailwind_sha256

  releases = [path] $src_base/releases.json
  releases_count = $releases_count
  releases_asset = $releases_asset

  linguas = $linguas
  xmllint = $xmllint
}

include ../www/

./: testscript file{releases.json} $out_root/www/exe{tailwindcss}
